/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.cbua.address.avro;

@org.apache.avro.specific.AvroGenerated
public interface AddressService {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"AddressService\",\"namespace\":\"com.cbua.address.avro\",\"types\":[{\"type\":\"record\",\"name\":\"CreateAddress\",\"fields\":[{\"name\":\"addressOne\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"addressTwo\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"city\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"zip\",\"type\":\"int\"},{\"name\":\"country\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}],\"messages\":{\"createAddress\":{\"request\":[{\"name\":\"createAddress\",\"type\":\"CreateAddress\"}],\"response\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},\"addUserToAddress\":{\"request\":[{\"name\":\"addressId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"userId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}],\"response\":\"null\"},\"getUserIdsByCountry\":{\"request\":[{\"name\":\"country\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}],\"response\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":[]}}}}");
  /**
   */
  java.lang.String createAddress(com.cbua.address.avro.CreateAddress createAddress);
  /**
   */
  void addUserToAddress(java.lang.String addressId, java.lang.String userId);
  /**
   */
  java.util.List<java.lang.String> getUserIdsByCountry(java.lang.String country);

  @org.apache.avro.specific.AvroGenerated
  public interface Callback extends AddressService {
    public static final org.apache.avro.Protocol PROTOCOL = com.cbua.address.avro.AddressService.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void createAddress(com.cbua.address.avro.CreateAddress createAddress, org.apache.avro.ipc.Callback<java.lang.String> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void addUserToAddress(java.lang.String addressId, java.lang.String userId, org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getUserIdsByCountry(java.lang.String country, org.apache.avro.ipc.Callback<java.util.List<java.lang.String>> callback) throws java.io.IOException;
  }
}