/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.cbua.address.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CreateAddress extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7721717614779674673L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CreateAddress\",\"namespace\":\"com.cbua.address.avro\",\"fields\":[{\"name\":\"addressOne\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"addressTwo\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"city\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"zip\",\"type\":\"int\"},{\"name\":\"country\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CreateAddress> ENCODER =
      new BinaryMessageEncoder<CreateAddress>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CreateAddress> DECODER =
      new BinaryMessageDecoder<CreateAddress>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CreateAddress> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CreateAddress> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CreateAddress> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CreateAddress>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CreateAddress to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CreateAddress from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CreateAddress instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CreateAddress fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String addressOne;
  @Deprecated public java.lang.String addressTwo;
  @Deprecated public java.lang.String city;
  @Deprecated public int zip;
  @Deprecated public java.lang.String country;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CreateAddress() {}

  /**
   * All-args constructor.
   * @param addressOne The new value for addressOne
   * @param addressTwo The new value for addressTwo
   * @param city The new value for city
   * @param zip The new value for zip
   * @param country The new value for country
   */
  public CreateAddress(java.lang.String addressOne, java.lang.String addressTwo, java.lang.String city, java.lang.Integer zip, java.lang.String country) {
    this.addressOne = addressOne;
    this.addressTwo = addressTwo;
    this.city = city;
    this.zip = zip;
    this.country = country;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return addressOne;
    case 1: return addressTwo;
    case 2: return city;
    case 3: return zip;
    case 4: return country;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: addressOne = value$ != null ? value$.toString() : null; break;
    case 1: addressTwo = value$ != null ? value$.toString() : null; break;
    case 2: city = value$ != null ? value$.toString() : null; break;
    case 3: zip = (java.lang.Integer)value$; break;
    case 4: country = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'addressOne' field.
   * @return The value of the 'addressOne' field.
   */
  public java.lang.String getAddressOne() {
    return addressOne;
  }


  /**
   * Sets the value of the 'addressOne' field.
   * @param value the value to set.
   */
  public void setAddressOne(java.lang.String value) {
    this.addressOne = value;
  }

  /**
   * Gets the value of the 'addressTwo' field.
   * @return The value of the 'addressTwo' field.
   */
  public java.lang.String getAddressTwo() {
    return addressTwo;
  }


  /**
   * Sets the value of the 'addressTwo' field.
   * @param value the value to set.
   */
  public void setAddressTwo(java.lang.String value) {
    this.addressTwo = value;
  }

  /**
   * Gets the value of the 'city' field.
   * @return The value of the 'city' field.
   */
  public java.lang.String getCity() {
    return city;
  }


  /**
   * Sets the value of the 'city' field.
   * @param value the value to set.
   */
  public void setCity(java.lang.String value) {
    this.city = value;
  }

  /**
   * Gets the value of the 'zip' field.
   * @return The value of the 'zip' field.
   */
  public int getZip() {
    return zip;
  }


  /**
   * Sets the value of the 'zip' field.
   * @param value the value to set.
   */
  public void setZip(int value) {
    this.zip = value;
  }

  /**
   * Gets the value of the 'country' field.
   * @return The value of the 'country' field.
   */
  public java.lang.String getCountry() {
    return country;
  }


  /**
   * Sets the value of the 'country' field.
   * @param value the value to set.
   */
  public void setCountry(java.lang.String value) {
    this.country = value;
  }

  /**
   * Creates a new CreateAddress RecordBuilder.
   * @return A new CreateAddress RecordBuilder
   */
  public static com.cbua.address.avro.CreateAddress.Builder newBuilder() {
    return new com.cbua.address.avro.CreateAddress.Builder();
  }

  /**
   * Creates a new CreateAddress RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CreateAddress RecordBuilder
   */
  public static com.cbua.address.avro.CreateAddress.Builder newBuilder(com.cbua.address.avro.CreateAddress.Builder other) {
    if (other == null) {
      return new com.cbua.address.avro.CreateAddress.Builder();
    } else {
      return new com.cbua.address.avro.CreateAddress.Builder(other);
    }
  }

  /**
   * Creates a new CreateAddress RecordBuilder by copying an existing CreateAddress instance.
   * @param other The existing instance to copy.
   * @return A new CreateAddress RecordBuilder
   */
  public static com.cbua.address.avro.CreateAddress.Builder newBuilder(com.cbua.address.avro.CreateAddress other) {
    if (other == null) {
      return new com.cbua.address.avro.CreateAddress.Builder();
    } else {
      return new com.cbua.address.avro.CreateAddress.Builder(other);
    }
  }

  /**
   * RecordBuilder for CreateAddress instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CreateAddress>
    implements org.apache.avro.data.RecordBuilder<CreateAddress> {

    private java.lang.String addressOne;
    private java.lang.String addressTwo;
    private java.lang.String city;
    private int zip;
    private java.lang.String country;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.cbua.address.avro.CreateAddress.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.addressOne)) {
        this.addressOne = data().deepCopy(fields()[0].schema(), other.addressOne);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.addressTwo)) {
        this.addressTwo = data().deepCopy(fields()[1].schema(), other.addressTwo);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.city)) {
        this.city = data().deepCopy(fields()[2].schema(), other.city);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.zip)) {
        this.zip = data().deepCopy(fields()[3].schema(), other.zip);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.country)) {
        this.country = data().deepCopy(fields()[4].schema(), other.country);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing CreateAddress instance
     * @param other The existing instance to copy.
     */
    private Builder(com.cbua.address.avro.CreateAddress other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.addressOne)) {
        this.addressOne = data().deepCopy(fields()[0].schema(), other.addressOne);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.addressTwo)) {
        this.addressTwo = data().deepCopy(fields()[1].schema(), other.addressTwo);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.city)) {
        this.city = data().deepCopy(fields()[2].schema(), other.city);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.zip)) {
        this.zip = data().deepCopy(fields()[3].schema(), other.zip);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.country)) {
        this.country = data().deepCopy(fields()[4].schema(), other.country);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'addressOne' field.
      * @return The value.
      */
    public java.lang.String getAddressOne() {
      return addressOne;
    }


    /**
      * Sets the value of the 'addressOne' field.
      * @param value The value of 'addressOne'.
      * @return This builder.
      */
    public com.cbua.address.avro.CreateAddress.Builder setAddressOne(java.lang.String value) {
      validate(fields()[0], value);
      this.addressOne = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'addressOne' field has been set.
      * @return True if the 'addressOne' field has been set, false otherwise.
      */
    public boolean hasAddressOne() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'addressOne' field.
      * @return This builder.
      */
    public com.cbua.address.avro.CreateAddress.Builder clearAddressOne() {
      addressOne = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'addressTwo' field.
      * @return The value.
      */
    public java.lang.String getAddressTwo() {
      return addressTwo;
    }


    /**
      * Sets the value of the 'addressTwo' field.
      * @param value The value of 'addressTwo'.
      * @return This builder.
      */
    public com.cbua.address.avro.CreateAddress.Builder setAddressTwo(java.lang.String value) {
      validate(fields()[1], value);
      this.addressTwo = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'addressTwo' field has been set.
      * @return True if the 'addressTwo' field has been set, false otherwise.
      */
    public boolean hasAddressTwo() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'addressTwo' field.
      * @return This builder.
      */
    public com.cbua.address.avro.CreateAddress.Builder clearAddressTwo() {
      addressTwo = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'city' field.
      * @return The value.
      */
    public java.lang.String getCity() {
      return city;
    }


    /**
      * Sets the value of the 'city' field.
      * @param value The value of 'city'.
      * @return This builder.
      */
    public com.cbua.address.avro.CreateAddress.Builder setCity(java.lang.String value) {
      validate(fields()[2], value);
      this.city = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'city' field has been set.
      * @return True if the 'city' field has been set, false otherwise.
      */
    public boolean hasCity() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'city' field.
      * @return This builder.
      */
    public com.cbua.address.avro.CreateAddress.Builder clearCity() {
      city = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'zip' field.
      * @return The value.
      */
    public int getZip() {
      return zip;
    }


    /**
      * Sets the value of the 'zip' field.
      * @param value The value of 'zip'.
      * @return This builder.
      */
    public com.cbua.address.avro.CreateAddress.Builder setZip(int value) {
      validate(fields()[3], value);
      this.zip = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'zip' field has been set.
      * @return True if the 'zip' field has been set, false otherwise.
      */
    public boolean hasZip() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'zip' field.
      * @return This builder.
      */
    public com.cbua.address.avro.CreateAddress.Builder clearZip() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'country' field.
      * @return The value.
      */
    public java.lang.String getCountry() {
      return country;
    }


    /**
      * Sets the value of the 'country' field.
      * @param value The value of 'country'.
      * @return This builder.
      */
    public com.cbua.address.avro.CreateAddress.Builder setCountry(java.lang.String value) {
      validate(fields()[4], value);
      this.country = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'country' field has been set.
      * @return True if the 'country' field has been set, false otherwise.
      */
    public boolean hasCountry() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'country' field.
      * @return This builder.
      */
    public com.cbua.address.avro.CreateAddress.Builder clearCountry() {
      country = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CreateAddress build() {
      try {
        CreateAddress record = new CreateAddress();
        record.addressOne = fieldSetFlags()[0] ? this.addressOne : (java.lang.String) defaultValue(fields()[0]);
        record.addressTwo = fieldSetFlags()[1] ? this.addressTwo : (java.lang.String) defaultValue(fields()[1]);
        record.city = fieldSetFlags()[2] ? this.city : (java.lang.String) defaultValue(fields()[2]);
        record.zip = fieldSetFlags()[3] ? this.zip : (java.lang.Integer) defaultValue(fields()[3]);
        record.country = fieldSetFlags()[4] ? this.country : (java.lang.String) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CreateAddress>
    WRITER$ = (org.apache.avro.io.DatumWriter<CreateAddress>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CreateAddress>
    READER$ = (org.apache.avro.io.DatumReader<CreateAddress>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.addressOne);

    out.writeString(this.addressTwo);

    out.writeString(this.city);

    out.writeInt(this.zip);

    out.writeString(this.country);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.addressOne = in.readString();

      this.addressTwo = in.readString();

      this.city = in.readString();

      this.zip = in.readInt();

      this.country = in.readString();

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.addressOne = in.readString();
          break;

        case 1:
          this.addressTwo = in.readString();
          break;

        case 2:
          this.city = in.readString();
          break;

        case 3:
          this.zip = in.readInt();
          break;

        case 4:
          this.country = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










