
###
GET http://localhost:8080/actuator/health


###
POST http://localhost:8080/users
Content-Type: application/json

{
  "firstName": "Foo",
  "lastName": "Bar",
  "email": "foo@bar.com",
  "password": "test",
  "address": {
    "addressOne": "addr one",
    "addressTwo": "addr two",
    "city": "Odessa",
    "zip": 6500,
    "country": "Ukraine"
  }
}
###
POST http://localhost:8080/users
Content-Type: application/json

{
  "firstName": "Foo",
  "lastName": "Bar",
  "email": "foo@bar.com2",
  "password": "test",
  "address": {
    "addressOne": "addr one",
    "addressTwo": "addr two",
    "city": "Odessa",
    "zip": 6500,
    "country": "US"
  }
}

###
GET http://localhost:8080/users?country=US
